name: Staging Phase

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_APP_NAME: "go-staging-rs"
          envkey_APP_ADDRESS: "8082"
          envkey_ENVIRONMENT: "dev"
          envkey_DB_ADDRESS: ${{ secrets.DEV_DBADDRESS }}
          envkey_DB_NAME: ${{ secrets.DEV_DBNAME }}
          envkey_DB_USERNAME: ${{ secrets.DEV_DBUSER }}
          envkey_DB_PASSWORD: ${{ secrets.DEV_DBPASS }}
          envkey_JWT_SECRET_KEY: ${{ secrets.DEV_SECRET_JWT_KEY }}
          envkey_AWS_S3_SECRET_KEY: ${{ secrets.AWS_S3_SECRET_KEY }}
          envkey_AWS_S3_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          envkey_AWS_S3_REGION: ${{ secrets.AWS_S3_REGION }}
          envkey_AWS_S3_URL: ${{ secrets.AWS_S3_URL }}
          directory: conf/
          file_name: .env
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set Up Docker Build
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/go-rs:be-dev-${{ github.sha }},${{ secrets.DOCKER_HUB_USERNAME }}/go-rs:be-dev-latest
      - name: Executing remote command using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_SERVER_DEV }}
          username: ${{ secrets.SSH_USERNAME_DEV }}
          password: ${{ secrets.SSH_PASSWORD_DEV }}
          port: ${{ secrets.SSH_PORT_DEV }}
          script: |
            cd ${{ secrets.FOLDER_DEV_PATH }} 
            docker compose -f docker-compose.dev.yml stop
            docker compose -f docker-compose.dev.yml rm -f
            docker rmi ${{ secrets.DOCKER_HUB_USERNAME }}/go-rs:be-dev-latest
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/go-rs:be-dev-latest
            docker compose -f docker-compose.dev.yml up -d
